services:
  - type: web
    name: words-whispers-django
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn mydjproject.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mydjproject.settings
      - key: PYTHON_VERSION
        value: 3.10
      - key: SECRET_KEY
        value: your-secret-key-here
      - key: DEBUG
        value: False
