# Generated by Django 5.2.4 on 2025-07-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
